> ### **Assignment 2 - Numpy Array Operations**



# Numpy functions


### numpy is a library used for numerical computations it has various functions and datastructures for efficiently organizing and interpreting the numbers

Write a short introduction about Numpy and list the chosen functions.

- function 1 - np.nditerate
- function 2 - np.concatenate
- function 3 - np.matmul
- function 4 - np.transpose
- function 5 - np.mean

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [ ]:
# List of functions explained
#- function 1 - np.nditerate
#- function 2 - np.concatenate
#- function 3 - np.matmul
#- function 4 - np.transpose
#- function 5 - np.mean

## Function 1 - np.nditerate()

used to iterate over ndarray and get their values for working

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])

for values in np.nditer(arr1):
    print(values)

1
2
3
4
5

Explanation about example

In [7]:
# order of iteration is matched through the memory layout and not the view


#default order = k
arr2 = np.array([[1, 0, 3, 0],
                [0, 6, 5, 3],
                [5, 8, 0, 0]])

print("memory layout wise ordering")
for values in np.nditer(arr2.T):
    print(values,end=" ")


# order = C  (row wise)
print("\nrow wise ordering")
for values in np.nditer(arr2, order='C'):
    print(values,end=" ")


# order = F  (col wise)
print("\ncol wise ordering")
for values in np.nditer(arr2, order='F'):
    print(values,end=" ")

memory layout wise ordering
1 0 3 0 0 6 5 3 5 8 0 0
row wise ordering
1 0 3 0 0 6 5 3 5 8 0 0
col wise ordering
1 0 5 0 6 8 3 5 0 0 3 0

Explanation about example

## Function 2 - np.concatenate

this function is used to merge two or more arrays in any of their axis

In [9]:
# Example 1 -
# default axis is 0 - row wise
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]

Explanation about example

In [10]:
# Example 2 -
arr3 = np.arange(20).reshape(4,5)
arr4 = np.arange(20,40).reshape(4,5)


#for concatenating horizontally no. of rows should equal
print(np.concatenate( (arr3,arr4),axis=1))



#for concatenating vertically no. of columns should equal
print(np.concatenate( (arr3,arr4),axis=0))

[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

Explanation about example

In [15]:
# Example 3 - merging different shapes using flatten function
arr5 = np.array([1,2,3,4,5,6])
arr6 = np.array([[6,7,8],
                [9,10,11]])


#flattening then merging
flattened = np.concatenate((arr5.flatten(),arr6.flatten()))
print(flattened.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]

## Function 3 - np.matmul

it is used to apply matrix multiplication (dot products for 2d arrays)

In [19]:
# Example 1 - number of first matrix columns should equal to number of second matrix rows

# shape is 2*3
mat1 = np.array([[1,2,3],[3,4,5]])

#shape is 3*3
mat2 = np.array([[5,6,7],[7,8,9],[9,8,7]])

print(np.matmul(mat1,mat2))

#we can also use @ operator
print(mat1@mat2)

[[46 46 46]
 [88 90 92]]
[[46 46 46]
 [88 90 92]]

Explanation about example

In [22]:
# Example 2 - matmul vs arithmetic multication *

# '*' operator is used to multiply two matriz element wise means that their shape should equal
mat3 = np.arange(15).reshape(3,5)
mat4 = np.arange(15,30).reshape(3,5)

print(mat3*mat4)


#this show an error
try:
  print(mat3@mat4)
except Exception as e:
  print(e)

[[  0  16  34  54  76]
 [100 126 154 184 216]
 [250 286 324 364 406]]
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

Explanation about example

In [31]:
# Example 3 - out parameter
# This parameter is used to restore the output of multiplication

#create a empty matrix
#we know that output matrix shape for mat1@mat2 is 2*3
output = np.empty((2,3),dtype = np.int8)


print(np.matmul(mat1,mat2,out=output))

[[46 46 46]
 [88 90 92]]

## Function 4 - np.transpose

it is used to change the dimension of an array

In [2]:
# Example 1 -
#default tranpose order is reverse of array dimension
# row becomes column and column becomes row

arr1 = np.arange(12).reshape(3,4)
print(arr1)

print(np.transpose(arr1))
# or
print(arr1.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Explanation about example

In [9]:
# Example 2
# explicitly specifying tranpose axis

arr2 = np.array([
      [[1,2,3,4,5],
       [6,7,8,9,10]],
      [[11,12,13,14,15],
       [16,17,18,19,20]]
])
print("pre transpose shape :- ",arr2.shape)


#depth becomes rows, row becomes col , col becomes depth
arr2 = np.transpose(arr2,axes=(1,2,0))

print("post transpose shape :- ",arr2.shape)

pre transpose shape :-  (2, 2, 5)
post transpose shape :-  (2, 5, 2)

## Function 5 - np.mean

this function is used to calculate the central tendency (average) of the array

In [ ]:
# Example 1 -
arr1 = np.arange(15).reshape(3,5)


# mean of whole array
print(np.mean(arr1))

Explanation about example

In [10]:
# Example 2 -
# mean along specified axis

print("mean along rows ")
print(np.mean(arr1,axis = 1))


print("mean along columns ")
print(np.mean(arr1,axis = 0))

mean along rows
[1.5 5.5 9.5]
mean along columns
[4. 5. 6. 7.]

Explanation about example

In [13]:
# Example 3
# keep the dimensions

print("Mean along rows (axis=0) with keepdims=True")
print(np.mean(arr1,axis=0,keepdims=True))

print("Mean along columns (axis=1) with keepdims=True")
print(np.mean(arr1,axis=1,keepdims=True))

Mean along rows (axis=0) with keepdims=True
[[4. 5. 6. 7.]]
Mean along columns (axis=1) with keepdims=True
[[1.5]
 [5.5]
 [9.5]]

## Conclusion

np.nditer efficiently iterates through one or more array

np.concatenate joins the sequence the arrays in existing dimension

np.matmul multiplies arrays using matrix multiplication rules

np.tranpose reorder the dimensions of an array

np.mean compute the arithmetic average of an array